#!/bin/bash -e

if command -v systemctl &> /dev/null ; then
  systemctl daemon-reload &> /dev/null
fi

if ! getent group minimega &> /dev/null ; then
    echo "Adding minimega group."
    groupadd --system minimega
else
    echo "minimega group already exists."
fi

chgrp -R minimega /usr/share/doc/minimega
chgrp -R minimega /opt/minimega
