#!/bin/bash

if command -v systemctl &> /dev/null ; then
  echo "Stopping minimega, miniweb, and phenix services..."

  for unit in phenix miniweb minimega; do
    systemctl stop $unit 2>&1
  done
fi
